// Variables definition
project_id              = "prj-tf-training"
default_region          = "us-central1"
default_zone            = "us-central1-a"
vpc_name                = "fdn-tst-vpc-01"
auto_create_subnetworks = "false"
delete_default_routes   = false
eip_name                = "fdn-tst-eip-01"
gcs_bucket_name         = "fdn-tst-bkt"